#!/bin/bash

# Import the colors
. "${HOME}/.cache/wal/colors.sh"

Shutdown()   	  { shutdown now    ;}
Lock & Sleep()    { i3lock-fancy && paplay ~/.config/polybar/sound.wav && systemctl suspend  ;}
Reboot()          { reboot          ;}

func="$(declare -F | awk '{print $3}' | dmenu -l 4 -i -p "Powermenu:" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" )"
[ -z "$func" ] || "$func"

